/* Moon — English catalogue.
 *
 * Key-for-key identical to lang.tr.js, in the same order, so a diff of the two
 * files reads as a translation and Moon.I18n._verify() can prove nothing is
 * missing on either side.
 *
 * Voice: an instrument, not a coach. Second person, no exclamation marks, no
 * emoji, no praise, no scolding. Verbs of measurement: left, passed, over,
 * measured, written. Every error says three things: what happened, why, and
 * what you can do now.
 *
 * ".one" / ".other" are the plural pair; the selector picks ".one" only when
 * params.count === 1. Keys ending in ".short" are the 320px variants.
 */
(function (global) {
  "use strict";

  var Moon = global.Moon || {};
  global.Moon = Moon;
  Moon.Lang = Moon.Lang || {};

  Moon.Lang.en = {

    /* ---------------------------------------------------------- about ---- */

    "about.appTitle": "Moon — a budget ledger",
    "about.title": "What Moon is",
    "about.body1": "Moon is a budget ledger that opens from a single HTML file. There is no server, no account, and no network request.",
    "about.body2": "Everything you write stays in this browser's own storage. Nobody but you reads it, because there is nowhere for it to go.",
    "about.body3": "To move it, download it as JSON from the Data section and restore it in another browser from the same place.",

    /* ------------------------------------------------------------ nav ---- */

    "nav.panel": "Panel",
    "nav.ledger": "Ledger",
    "nav.limits": "Limits",
    "nav.recurring": "Recurring",
    "nav.goals": "Goals",
    "nav.debts": "Debts",
    "nav.accounts": "Accounts",
    "nav.investments": "Investments",
    "nav.data": "Data",
    "nav.more": "More",

    /* --------------------------------------------------------- common ---- */

    "common.save": "Save",
    "common.cancel": "Cancel",
    "common.more": "More",
    "common.details": "Details",
    "common.notSaved": "The change was not saved; the old value is back.",
    "limits.edit": "Change the period limit: {amount}",
    "common.delete": "Delete",
    "common.edit": "Edit",
    "common.copy": "Duplicate",
    "common.close": "Close",
    "common.add": "Add",
    "common.confirm": "Confirm",
    "common.undo": "Undo",
    "common.all": "All",
    "common.unclassified": "Unclassified",
    "common.today": "Today",
    "common.yesterday": "Yesterday",
    "common.expense": "Expense",
    "common.income": "Income",
    "common.fixed": "Fixed",
    "common.variable": "Variable",
    "common.none": "None",
    "common.showNumbers": "Show the numbers",
    "common.noNumbers": "No numbers to show.",
    "common.hideNumbers": "Hide the numbers",
    "common.loading": "Reading",
    "common.search": "Search",
    "common.period": "Period",
    "common.currency": "Currency",
    "common.language": "Language",
    "common.theme": "Theme",
    "common.theme.system": "System",
    /* The key here names the stored value, not the word on screen, and §2.2
       renamed the two surfaces while leaving the stored dial and paper alone so
       that a setting written by an older build still reads. The label for dial
       is therefore Night and the label for paper is Dawn. The .night and .dawn
       keys carry the same two words under the names the interface uses from
       here on, so the theme control reads the same whichever it asks for. */
    "common.theme.dial": "Night",
    "common.theme.paper": "Dawn",
    "common.theme.night": "Night",
    "common.theme.dawn": "Dawn",
    "common.theme.prism": "Prism",
    "common.lang.tr": "Turkish",
    "common.lang.en": "English",
    "common.dayCount.one": "{count} day",
    "common.dayCount.other": "{count} days",
    "common.undoSeconds": "{seconds} seconds",

    /* ---------------------------------------------------------- panel ---- */

    "panel.dailyAllowance": "Daily allowance left",
    "panel.dayCount": "day {dayIndex} of {days}",

    "panel.state.ok.label": "Daily allowance left",
    "panel.state.ok.body": "{amount} left over {days} days.",
    "panel.state.ok.body.short": "{amount} over {days} days.",

    "panel.state.noLimits.label": "Spent this period",
    "panel.state.noLimits.body": "You have not set a limit yet, so the daily allowance cannot be measured. The moment you set one, this number becomes the allowance.",
    "panel.state.noLimits.body.short": "No limit, no allowance yet.",
    "panel.state.noLimits.action": "Set a limit",

    "panel.state.overspent.label": "Over the limit",
    "panel.state.overspent.body": "You are {amount} over the total of your limits, with {days} days left and nothing budgeted.",
    "panel.state.overspent.body.short": "{amount} over, {days} days unbudgeted.",

    "panel.state.lastDay.label": "Today's allowance",
    "panel.state.lastDay.body": "Today is the last day of the period, with {amount} left.",
    "panel.state.lastDay.body.short": "Last day, {amount} left.",

    "panel.state.pastPeriod.label": "Period total",
    "panel.state.pastPeriod.body": "{period} is closed. You used {pct}% of your limits.",
    "panel.state.pastPeriod.body.short": "{period} closed, {pct}% of limits.",

    "panel.spentToday": "You spent {spent} today, and {left} of today's allowance is left.",
    "panel.spentToday.short": "Today {spent}, {left} left.",

    "panel.paceLine": "The month is {periodPct}% through and you have used {spentPct}% of your limits.",
    "panel.paceLine.short": "Month {periodPct}%, limits {spentPct}%.",

    "panel.fixedReserved.one": "{count} fixed payment, {amount} set aside.",
    "panel.fixedReserved.other": "{count} fixed payments, {amount} set aside.",
    "panel.fixedReserved.short": "Fixed payments: {amount} set aside.",

    "panel.entryCount.one": "{count} entry written this period.",
    "panel.entryCount.other": "{count} entries written this period.",

    "panel.pending.one": "{count} recurring payment is waiting, {amount} in total.",
    "panel.pending.other": "{count} recurring payments are waiting, {amount} in total.",
    "panel.pending.short": "{count} waiting to be written.",
    "panel.pending.action": "Write the pending ones",
    "panel.pending.review": "Look in Recurring",

    "panel.moreCategories.one": "{count} more category",
    "panel.moreCategories.other": "{count} more categories",

    "panel.dropHint": "You can drop a bank statement onto this strip.",
    "panel.dropActive": "Drop the file and we'll map the columns together.",

    "panel.chart.trail.title": "Allowance trail",
    "panel.chart.trail.body": "The daily allowance measured on each day of the period. The horizontal line is the allowance the period started with: above it the allowance grew, below it the allowance melted.",
    "panel.chart.flow.title": "Day seismograph",
    "panel.chart.flow.body": "One bar per day: above the middle line is income, below it is expense. Weekends get a darker tick on the baseline.",
    "panel.chart.cumulative.title": "Cumulative period",
    "panel.chart.cumulative.body": "Total expense from the start of the period until today. The diagonal spreads the limit day by day; the dotted trace is last period.",
    "panel.chart.cumulative.crossed": "The pace was crossed on {date}.",
    "panel.chart.year.title": "Year grid",
    "panel.chart.year.body": "The last twelve periods by category. Cell density comes from line spacing rather than colour, so it reads in black and white too.",
    "panel.chart.reading": "{date} — {amount}",

    /* --------------------------------------------------------- ledger ---- */

    "ledger.title": "Ledger",
    "ledger.detail.created": "Written at",
    "ledger.detail.mark": "Margin mark",
    "ledger.detail.source": "Came from",
    "ledger.keys": "Move through the list with the up and down arrows: Space selects a row, Enter edits it, Delete removes it, and the right arrow steps into the row's actions.",
    "ledger.filter.search": "Search",
    "ledger.filter.search.hint": "Looks inside notes and category names.",
    "ledger.filter.period": "Period",
    "ledger.filter.category": "Category",
    "ledger.filter.category.all": "All categories",
    "ledger.filter.direction": "Direction",
    "ledger.filter.direction.all": "Expense and income",
    "ledger.filter.source": "Source",
    "ledger.filter.source.all": "All sources",
    "ledger.filter.source.manual": "Typed by hand",
    "ledger.filter.source.csv": "From a statement",
    "ledger.filter.source.recurring": "Recurring",
    "ledger.filter.source.sample": "Sample",
    "ledger.filter.unconfirmed": "Only waiting for confirmation",
    "ledger.filter.clear": "Clear the filter",
    "ledger.density": "Row density",
    "ledger.density.dense": "Dense",
    "ledger.density.roomy": "Roomy",
    "ledger.summary": "Showing {shown} of {count} entries, {total} in total.",
    "ledger.summary.short": "{shown}/{count} entries, {total}.",
    "ledger.count.one": "{count} entry",
    "ledger.count.other": "{count} entries",
    "ledger.total": "Total {total}",
    "ledger.dayTotal": "Day total {amount}",
    "ledger.col.date": "Date",
    "ledger.col.category": "Category",
    "ledger.col.note": "Note",
    "ledger.col.amount": "Amount",
    "ledger.action.edit": "Edit this entry",
    "ledger.action.copy": "Duplicate this entry",
    "ledger.action.delete": "Delete this entry",
    "ledger.delete.title": "Delete this entry?",
    "ledger.delete.body": "Delete this entry? You will have eight seconds to undo it.",
    "ledger.delete.confirm": "Delete",
    "ledger.deleted": "The entry was deleted.",
    "ledger.deletedMany.one": "{count} entry was deleted.",
    "ledger.deletedMany.other": "{count} entries were deleted.",
    "ledger.undone": "The deletion was undone.",
    "ledger.undo.hint": "You have {seconds} seconds to undo it.",
    "ledger.form.title.new": "Write an entry",
    "ledger.form.title.edit": "Edit the entry",
    "ledger.form.submit": "Write entry",
    "ledger.form.submit.edit": "Update entry",
    "ledger.form.fixedHint": "A fixed entry stays out of the daily allowance pool and shows up as money set aside.",
    "ledger.saved": "Saved.",
    "ledger.copied": "The entry was duplicated and dated today.",
    "ledger.unconfirmed.note": "This entry came from a statement and is not confirmed yet. The mark in the right margin says so.",
    "ledger.unconfirmedCount.one": "{count} entry is waiting for confirmation.",
    "ledger.unconfirmedCount.other": "{count} entries are waiting for confirmation.",
    "ledger.confirmAll": "Confirm all",
    "ledger.confirmedCount.one": "{count} entry was confirmed.",
    "ledger.confirmedCount.other": "{count} entries were confirmed.",

    /* --------------------------------------------------------- limits ---- */

    "limits.title": "Limits",
    /* The row's own face is also the button that changes it: pressing it
       unfolds the colour and icon pickers. The name says what unfolds, because
       what sits on the button is a dot and a glyph rather than any text. */
    "limits.category.appearance": "Colour and icon",
    "limits.category.archive": "Archive",
    "limits.category.unarchive": "Unarchive",
    "limits.category.removed": "{name} deleted, {count} entries moved to Other.",
    "limits.category.removed.one": "{name} deleted, {count} entry moved to Other.",
    "limits.category.removed.other": "{name} deleted, {count} entries moved to Other.",
    "limits.drift.ahead": "{amount} ahead",
    "limits.drift.behind": "{amount} behind",
    "limits.drift.over": "{amount} over",
    "limits.drift.done": "fully paid",
    "limits.fixed.note": "Fixed costs are held out of the daily-allowance pool.",
    "limits.year.title": "The year",
    "limits.year.key": "Density",
    "limits.suggest.title": "Suggest limits from your data",
    "limits.suggest.empty": "I found nothing in your closed periods to suggest a limit from.",
    "limits.suggest.basis.one": "Read {count} complete period, {entries} entries. The period in progress was left out.",
    "limits.suggest.basis.other": "Read {count} complete periods, {entries} entries. The period in progress was left out.",
    "limits.suggest.confidence.high.one": "measured over {count} period",
    "limits.suggest.confidence.high.other": "measured over {count} periods",
    "limits.suggest.confidence.medium.one": "measured over {count} period",
    "limits.suggest.confidence.medium.other": "measured over {count} periods",
    "recurring.detect.periods.one": "seen in {count} period",
    "recurring.detect.periods.other": "seen in {count} separate periods",
    "limits.suggest.body": "I read your closed months and propose a limit for each category. Change what you like, leave out what you do not.",
    "limits.suggest.action": "Suggest limits",
    "limits.suggest.apply": "Write the selected ones",
    "limits.suggest.basis": "Read {count} complete periods, {entries} entries. The period in progress was left out.",
    "limits.suggest.none": "No period has closed yet. Once one completes, I can suggest limits from your own data.",
    "limits.suggest.confidence.high": "measured over {count} periods",
    "limits.suggest.confidence.medium": "measured over {count} periods",
    "limits.suggest.confidence.low": "Seen in one period only; a thin suggestion",
    "limits.suggest.current": "currently {amount}",
    "limits.suggest.applied.one": "{count} limit written.",
    "limits.suggest.applied.other": "{count} limits written.",
    "limits.reading.ahead": "{amount} ahead",
    "limits.reading.behind": "{amount} behind",
    "limits.reading.over": "{amount} over",
    "limits.reading.done": "paid in full",
    "limits.pct": "{pct}%",
    "limits.pace": "{pace}% expected",
    "limits.overLine": "You are {amount} over your {name} limit. If the limit is not realistic, you can update it here.",
    "limits.total": "Limits total {amount}",
    "limits.variableTotal": "Pool behind the allowance {amount}",
    "limits.form.title.new": "Set a limit",
    "limits.form.title.edit": "Update the limit",
    "limits.form.amount": "Limit for the period",
    "limits.form.amount.hint": "The ceiling you give this category for one period.",
    "limits.form.remove": "Remove the limit",
    "limits.saved": "The limit was saved.",
    "limits.removed": "The limit was removed.",
    "limits.aria.meter": "{name}: {pct}% of the limit used, {pace}% expected.",
    "limits.aria.over": "{name}: {amount} over the limit, spilling past the scale.",
    "limits.aria.pace": "Pace mark at {pace}%.",
    "limits.overflow.note": "The part over the limit passes the end cap and spills into the reading column. The percentage, the hatch pattern and the sentence all say the same thing.",

    /* ------------------------------------------------------ recurring ---- */

    "recurring.title": "Recurring payments",
    "recurring.detect.title": "Payments that repeat",
    "recurring.detect.body": "Some entries in your ledger come back month after month. Writing a rule moves them to fixed costs and takes them out of the daily-allowance pool.",
    "recurring.detect.none": "I could not find a payment that repeats.",
    "recurring.detect.periods": "seen in {count} separate periods",
    "recurring.detect.varies": "The amount varies; median {amount}",
    "recurring.detect.hasRule": "A rule already covers this.",
    "recurring.detect.action": "Write a rule and fix it",
    "recurring.detect.actionPlain": "Write the rule only",
    "recurring.detect.promoted": "The rule is written. Nothing was added for this period; it comes up for approval next period.",
    "recurring.detect.markedFixed.one": "{count} entry marked fixed; it left the daily-allowance pool.",
    "recurring.detect.markedFixed.other": "{count} entries marked fixed; they left the daily-allowance pool.",
    "recurring.active": "Active",
    "recurring.paused": "Paused",
    "recurring.form.title.new": "Add a recurring payment",
    "recurring.form.title.edit": "Edit the recurring payment",
    "recurring.form.dayOfMonth": "Day of the month",
    "recurring.form.dayOfMonth.hint": "On short months it clips to the last day, then returns to this day.",
    "recurring.form.fixedHint": "A fixed recurring payment stays out of the daily allowance pool.",
    "recurring.next": "Next on {date}, {amount}",
    "recurring.pendingCount.one": "{count} payment is waiting.",
    "recurring.pendingCount.other": "{count} payments are waiting.",
    "recurring.pendingSince": "Waiting since {date}.",
    "recurring.write": "Write this payment",
    "recurring.writeAll": "Write every pending payment",
    "recurring.writtenCount.one": "{count} entry was written.",
    "recurring.writtenCount.other": "{count} entries were written.",
    "recurring.pause": "Pause",
    "recurring.resume": "Resume",
    "recurring.pausedToast": "{name} is paused and writes no new entries.",
    "recurring.resumedToast": "{name} runs again.",
    "recurring.saved": "The recurring payment was saved.",
    "recurring.delete.title": "Delete this recurring payment?",
    "recurring.delete.body": "The rule goes. Entries already written from it stay in the ledger.",

    /* ---------------------------------------------------------- goals ---- */

    "goals.title": "Goals",
    "goals.form.saved": "Already saved",
    "goals.form.title.new": "Add a goal",
    "goals.form.title.edit": "Edit the goal",
    "goals.form.target": "Target amount",
    "goals.form.dueDate": "Target date",
    "goals.form.dueDate.hint": "Leave it empty and I will only measure what is saved.",
    "goals.saved": "The goal was saved.",
    "goals.progress": "{saved} saved, {remaining} to go.",
    "goals.progress.short": "{saved} / {target}",
    "goals.perMonth": "Set aside {amount} a month and it fills on {date}.",
    "goals.monthsLeft.one": "{count} month left.",
    "goals.monthsLeft.other": "{count} months left.",
    "goals.done": "Goal filled: {amount} saved, {days} days early.",
    "goals.overdue": "The date passed with {remaining} missing.",
    "goals.contribute": "Add a contribution",
    "goals.contributionAdded": "The contribution was saved.",
    "goals.contributionCount.one": "{count} contribution",
    "goals.contributionCount.other": "{count} contributions",
    "goals.delete.title": "Delete this goal?",
    "goals.delete.body": "The goal and its contributions go. Entries in the ledger are untouched.",
    "goals.note": "Goals stay out of the allowance and limit math.",

    /* ---------------------------------------------------------- debts ---- */

    "debts.title": "Debts and credits",
    "debts.direction.owedToMe": "Owed to me",
    "debts.direction.iOwe": "I owe",
    "debts.form.title.new": "Add a debt or a credit",
    "debts.form.title.edit": "Edit the record",
    "debts.form.person": "Person",
    "debts.form.direction": "Direction",
    "debts.form.dueDate": "Due date",
    "debts.form.dueDate.hint": "You can leave it empty.",
    "debts.saved": "Saved.",
    "debts.totals": "Owed to you {owedToMe}, you owe {iOwe}, net {net}.",
    "debts.totals.short": "Owed {owedToMe}, you owe {iOwe}.",
    "debts.openCount.one": "{count} record is open.",
    "debts.openCount.other": "{count} records are open.",
    "debts.settle": "Settle",
    "debts.settled": "Settled on {date}.",
    "debts.settledToast": "The record was settled.",
    "debts.reopen": "Reopen",
    "debts.dueIn.one": "{count} day until it is due.",
    "debts.dueIn.other": "{count} days until it is due.",
    "debts.overdueBy.one": "{count} day past due.",
    "debts.overdueBy.other": "{count} days past due.",
    "debts.delete.title": "Delete this record?",
    "debts.delete.body": "This debt record goes. Entries in the ledger are untouched.",
    "debts.note": "Debts and credits stay out of the allowance and limit math.",

    /* ------------------------------------------------------- accounts ---- */

    "accounts.title": "Accounts",
    "accounts.name": "Account name",
    /* Repairing a record whose name could not be read, the Store has to write
       some name: an empty one leaves the card indistinguishable from the next
       nameless card. This says the record arrived without a name, where the
       categories' "Unclassified" would be the wrong word for an account. */
    "accounts.untitled": "Unnamed account",
    "accounts.balance": "Balance",
    /* UI.inlineValue turns a labelKey into an aria-label, and an aria-label
       stands in place of the text beneath it rather than adding to it. So
       these two carry the reading itself; without it the control announces
       only what it is and drops the figure a reader came for. */
    "accounts.name.edit": "Change the account name: {name}",
    "accounts.balance.edit": "Change the balance: {amount}",
    "accounts.opening": "Opening balance",
    "accounts.opening.hint": "Entries are added on top of this amount. A credit card can be negative.",
    "accounts.total": "Accounts total {amount}",
    /* The card draws whichever period the header is showing, not necessarily
       the month we are in. Name a month and browsing back to September prints
       September's movement under the words "this month"; the sentence names no
       period and so stays true for every one of them. */
    "accounts.flow": "{in} in and {out} out this period.",
    "accounts.flow.none": "No movement in this account this period.",
    "accounts.kind.cash": "Cash",
    "accounts.kind.bank": "Bank",
    "accounts.kind.card": "Credit card",
    "accounts.kind.savings": "Savings",
    "accounts.form.title.new": "Add an account",
    "accounts.form.title.edit": "Edit the account",
    "accounts.form.submit": "Add the account",
    "accounts.form.submit.edit": "Update the account",
    "accounts.addChip": "Add account",
    "accounts.archive": "Archive",
    "accounts.unarchive": "Unarchive",
    "accounts.archived": "Archived",
    "accounts.delete.title": "Delete this account?",
    "accounts.delete.body": "The account goes and the entries stay. Entries linked to it remain in the ledger and only lose the link.",
    "accounts.saved": "The account was saved.",
    "accounts.removed": "{name} was deleted and {count} entries lost their account link.",
    "accounts.removed.one": "{name} was deleted and {count} entry lost its account link.",
    "accounts.removed.other": "{name} was deleted and {count} entries lost their account link.",
    "accounts.empty.heading": "No accounts yet.",
    "accounts.empty.body": "Write down where your money sits: cash, a bank, a card, savings. I add the balances up here and carry them into your net worth.",
    "accounts.empty.action": "Add the first account",

    /* ---------------------------------------------------- investments ---- */

    "investments.title": "Investments",
    "investments.name": "Holding name",
    /* The holding side of the nameless record, with its own text so that a
       holding is never named as though it were an account. */
    "investments.untitled": "Unnamed holding",
    "investments.quantity": "Quantity",
    "investments.quantity.hint": "At most four decimal places are read; 0.5 works.",
    "investments.unitCost": "Unit cost",
    "investments.unitCost.hint": "What one unit cost you.",
    "investments.unitPrice": "Unit price",
    "investments.unitPrice.hint": "What one unit is worth today. You type the price; Moon never goes online.",
    "investments.value": "Value",
    "investments.cost": "Cost",
    "investments.gain": "Gain",
    "investments.gainPct": "{pct}%",
    "investments.gainLine": "Gain {amount}, {pct}%",
    "investments.qtyLine": "{quantity} × {price}",
    "investments.priceDate": "Price updated on {date}.",
    "investments.updatePrice": "Update the price",
    "investments.priceSaved": "The new price was saved.",
    "investments.byKind": "By kind",
    "investments.byKind.row": "{name}, {amount}, {pct}% of the total",
    "investments.chart.none": "The value trail needs at least two prices. The moment you type a second one, the chart appears here.",
    "investments.kind.stock": "Shares",
    "investments.kind.fund": "Fund",
    "investments.kind.crypto": "Crypto",
    "investments.kind.gold": "Gold",
    "investments.kind.fx": "Currency",
    "investments.kind.property": "Property",
    "investments.kind.other": "Other",
    "investments.form.title.new": "Add a holding",
    "investments.form.title.edit": "Edit the holding",
    "investments.form.submit": "Add the holding",
    "investments.form.submit.edit": "Update the holding",
    /* The archive actions read the same as their siblings on the accounts side
       but carry keys of their own, so that a language needing a different verb
       for a holding does not drag the account cards' wording along with it. */
    "investments.archive": "Archive",
    "investments.unarchive": "Unarchive",
    "investments.archived": "Archived",
    "investments.delete.title": "Delete this holding?",
    "investments.delete.body": "The holding and its price history go. Entries in the ledger are untouched.",
    "investments.saved": "The holding was saved.",
    "investments.removed": "{name} was deleted.",
    "investments.empty.heading": "No holdings yet.",
    "investments.empty.body": "Write what you hold: shares, a fund, gold, currency, a flat. Give me the quantity and the unit price and I measure the value into your net worth.",
    "investments.empty.action": "Add the first holding",

    /* ------------------------------------------------------- networth ---- */

    "networth.label": "Net worth",
    "networth.assets": "Assets",
    "networth.liabilities": "Liabilities",
    "networth.cash": "Cash",
    "networth.investments": "Investments",
    "networth.owedToMe": "Owed to me",
    "networth.iOwe": "I owe",
    "networth.day": "day {dayIndex} of {days}",
    "networth.empty": "Net worth has not been measured yet. Write an account or a holding and it shows up here; an unmeasured number is not printed as a zero.",

    /* ----------------------------------------------------------- data ---- */

    "data.title": "Data",

    "data.backup.title": "Back up",
    "data.backup.body": "All your data goes into one JSON file. The file stays on your own machine.",
    "data.backup.action": "Download the backup",
    "data.backup.done": "{file} was downloaded. All your data is in that file; in another browser you can restore it from the Data section.",
    "data.backup.fallback": "The browser blocked the download. The backup text is selected below; copy it and save it to a file.",
    "data.backup.copy": "Copy the text",
    "data.backup.last": "Last backup {date}.",
    "data.backup.nudge": "{count} changes since your last backup. Backing up takes ten seconds.",
    "data.backup.nudge.never": "You have not backed up yet. Backing up takes ten seconds.",

    "data.restore.title": "Restore",
    "data.restore.dropped.one": "1 record in the file could not be read and was left out.",
    "data.restore.dropped.other": "{count} records in the file could not be read and were left out.",
    "data.restore.repaired.one": "1 record was repaired on the way in.",
    "data.restore.repaired.other": "{count} records were repaired on the way in.",
    "data.restore.body": "Choose the JSON file you downloaded earlier.",
    "data.restore.mode": "How to restore",
    "data.restore.mode.replace": "Replace what is here",
    "data.restore.mode.merge": "Add on top of what is here",
    "data.restore.action": "Choose the file",
    "data.restore.done": "{entries} entries and {categories} categories were restored.",
    "data.restore.skipped.one": "{count} entry was skipped; the same id was already here.",
    "data.restore.skipped.other": "{count} entries were skipped; the same ids were already here.",
    "data.restore.confirm.title": "What is here will be replaced.",
    "data.restore.confirm.body": "Restoring erases the data in this browser and writes the file instead. Back up first, then carry on.",

    "data.sample.title": "Sample month",
    "data.sample.body": "A made-up September, 61 entries, if you'd rather look around first. One click clears it.",
    "data.sample.on": "Open the sample month",
    "data.sample.off": "Clear the sample data",
    "data.sample.strip": "Sample data is on. It never mixes with your own entries and one click clears it.",
    "sample.catName": "{name} (sample)",
    "data.sample.cleared": "The sample data was cleared.",

    "data.wipe.title": "Erase everything",
    "data.wipe.body": "Entries, limits, goals, debts and settings all go.",
    "data.wipe.action": "Erase everything",
    "data.wipe.confirm.title": "Erase everything?",
    "data.wipe.confirm.body": "Every bit of Moon data in this browser is erased and cannot be brought back. If you have downloaded a backup, you can carry on.",
    "data.wipe.done": "All data was erased.",

    "data.settings.title": "Settings",
    "data.settings.currency.hint": "Existing amounts are not converted. An entry of 1.000 ₺ reads as 1,000 $.",
    "data.settings.monthStartDay": "Day the period starts",
    "data.settings.monthStartDay.hint": "If you are paid on the 15th, write 15; the period starts on that day.",
    "data.settings.overflowMark": "Over-limit mark",
    "data.settings.overflowMark.pigment": "Pigment",
    "data.settings.overflowMark.flare": "Flare",
    "data.settings.overflowMark.hint": "Chooses which ink marks an overrun. The hatch pattern, the percentage and the sentence stay either way.",

    "data.storage.title": "Storage",
    "data.storage.usage": "{used} used across {count} entries.",

    "data.readOnly": "This browser cannot store data, so the session is read only. It may be a private window or storage that is switched off; what you write is lost when the tab closes, so download the JSON first.",
    "data.error.corrupt": "The saved data could not be read and looked damaged. It was not deleted, only set aside, and the app opened with an empty ledger. If you have a backup, Restore will bring it back.",
    "data.error.newerSchema": "The data in this browser comes from a newer version of Moon. To avoid reading it wrongly and damaging it, the session opened read only; update the app and it becomes writable again.",
    "data.error.unknownSchema": "The saved data has an unrecognised version. Nothing was touched and the session opened read only. You can download your backup and restore into a clean install.",

    "data.quota.title": "The change could not be saved.",
    "data.quota.body": "The browser's storage is full. What is on screen is intact; download the JSON and delete old entries, and writing works again.",
    "data.quota.action": "Download the JSON",

    /* ------------------------------------------------------------ csv ---- */

    "csv.title": "Import a statement",
    "csv.step": "Step {step} of {total}",
    "csv.back": "Back",
    "csv.next": "Next",

    "csv.step1.title": "File",
    "csv.step1.body": "Drop the CSV file here or choose it. The file never leaves this browser.",
    "csv.step1.choose": "Choose a file",
    "csv.step1.accept": "Accepted: .csv and .txt",
    "csv.step1.big": "The file is {size}. Reading may take a moment; the page keeps working meanwhile.",

    "csv.step2.title": "Reading",
    "csv.step2.body": "Here is what I read from the file. Change anything that is wrong and the preview updates at once.",
    "csv.delimiter": "Delimiter",
    "csv.delimiter.semicolon": "Semicolon ( ; )",
    "csv.delimiter.comma": "Comma ( , )",
    "csv.delimiter.tab": "Tab",
    "csv.delimiter.pipe": "Pipe ( | )",
    "csv.encoding": "Encoding",
    "csv.encoding.utf8": "UTF-8",
    "csv.encoding.w1254": "Windows-1254 (Turkish)",
    "csv.encoding.utf16le": "UTF-16LE",
    "csv.headerRow": "Header row",
    "csv.headerRow.hint": "Free text at the top of a statement is skipped.",
    "csv.decimal": "Decimal mark",
    "csv.decimal.comma": "Comma ( 1.234,56 )",
    "csv.decimal.dot": "Dot ( 1,234.56 )",
    "csv.dateOrder": "Date order",
    "csv.dateOrder.dmy": "Day, month, year",
    "csv.dateOrder.mdy": "Month, day, year",
    "csv.dateSample": "The file says {raw}, and I read it as {parsed}.",
    "csv.preview": "First {count} rows",
    "csv.role": "Column role",
    "csv.column": "column {index}",
    "csv.role.ignore": "Ignore",
    "csv.role.date": "Date",
    "csv.role.note": "Note",
    "csv.role.amount": "Amount",
    "csv.role.debit": "Debit",
    "csv.role.credit": "Credit",
    "csv.role.category": "Category",
    "csv.role.confidence": "{pct}% could be read",

    /* The import no longer stops to ask which column holds the date: the roles
       are inferred from the data and the preview opens straight away. These
       keys are the words that step needs — one line of account for the guess,
       the control that reopens the mapping step when the guess is wrong, and
       the count of page lines that were never transactions. The last one is
       kept deliberately flat: an interest-rate table left out of an import is
       a fact about the statement, not a fault of the reader's, so it must not
       read like a warning. */
    "csv.roles.guessed": "I worked the columns out myself and read {count} rows. If I got one wrong you can fix it.",
    "csv.roles.fix": "Fix the columns",
    "csv.rows.skipped.one": "{count} line on the page was not a transaction — a rate table, a total, an address — and was left out.",
    "csv.rows.skipped.other": "{count} lines on the page were not transactions — rate tables, totals, addresses — and were left out.",

    "csv.signRule": "Sign rule",
    "csv.signRule.negativeIsExpense": "Negative means expense",
    "csv.signRule.positiveIsExpense": "Positive means expense (a credit card)",
    "csv.signRule.debitCredit": "Debit and credit in separate columns",
    "csv.defaultCategory": "Default category",
    "csv.defaultCategory.hint": "Rows whose category cannot be read land here.",

    "csv.step3.title": "Review",
    "csv.step3.summary": "{total} rows read. {ok} can be added, {duplicate} are duplicates, {rejected} were skipped.",
    "csv.step3.range": "Dates run from {from} to {to}.",
    "csv.step3.sums": "Expense {out}, income {in}.",
    "csv.duplicates.title": "Duplicate rows",
    "csv.duplicates.body": "The ledger already holds these rows. The ticked ones are skipped; if two real expenses fell on the same day for the same amount, untick it.",
    "csv.duplicates.row": "Row {line}: {date}, {amount}",
    "csv.skipped.title": "Skipped rows",
    "csv.skipped.body": "No entry could be made from these rows.",
    "csv.skipped.row": "Row {line}: {reason}",
    "csv.reason.badDate": "the date could not be read",
    "csv.reason.badAmount": "the amount could not be read",
    "csv.reason.zeroAmount": "the amount is zero",
    "csv.reason.raggedRow": "the field count does not match the header",
    "csv.reason.unclosedQuote": "a quote is left open",
    "csv.reason.repeatedHeader": "a repeated header row",
    "csv.reason.summaryRow": "a summary row",

    "csv.step4.title": "Writing",
    "csv.step4.action": "Write the entries",
    "csv.done.one": "{count} entry was added and waits for confirmation.",
    "csv.done.other": "{count} entries were added and wait for confirmation.",
    "csv.done.body": "They show up in the ledger with a margin mark. The confirm-all button sits in the Ledger section.",

    "csv.err.noDate": "I could not find a date column in this file. Show me which column holds the date and I will carry on.",
    "csv.err.noAmount": "I could not find an amount column in this file. Pick the column that carries the amount and I will carry on.",
    "csv.err.empty": "There is no row to read in this file. It may be empty, or another sheet may have been saved; save it as CSV and try again.",
    "csv.err.notCsv": "I could not read this file as CSV. Choose a file ending in .csv or .txt.",
    "pdf.err.notPdf": "This file did not read as a PDF. Pick the original the bank gave you; it may have been re-saved or downloaded only partly.",
    "pdf.err.encrypted": "This PDF is password protected. Open it where the password is known, save a copy without one, and try again.",
    "pdf.err.noText": "There is no text inside this PDF, only a picture of the page — that is how a scanned or photographed statement arrives. If your bank offers a CSV, or a PDF with real text in it, I can read that.",
    /* Separate from pdf.err.noText because the cause and the cure are both
       different: such a page does carry a little text — a title, a card line —
       so the file never looks empty, and it usually came out of a phone
       banking app that draws the statement as a picture. Naming web banking
       and CSV gives the reader somewhere to go in one step. No word for
       "error" appears in it, because nothing they did was wrong. */
    "pdf.err.scanned": "This PDF's page is a picture: there is almost no text in it to read. A statement saved from a phone banking app, or a scanned sheet of paper, usually arrives like this. The same statement is nearly always in your bank's web banking as a CSV or as a PDF with real text in it, and I read both.",
    "pdf.warn.fewRows": "Only a few rows came out of this PDF. If the preview below looks short, the bank's CSV will be more reliable.",
    "pdf.reading": "Reading the PDF…",
    "pdf.read.summary": "Read {lines} lines from {pages} pages.",
    /* A statement is read twice over — once off the page's column grid, once
       line by line looking for a date next to an amount — and the better of
       the two wins. The small print under the preview says which one won,
       because that is the first thing worth knowing when a column looks
       wrong, and the reader has no console to ask. */
    "pdf.read.table": "Columns taken from the page's own grid.",
    "pdf.read.lines": "Each line read for a date and an amount.",
    "pdf.note": "Columns in a PDF are worked out from where the words sit, not from a delimiter. Have a look at the rows below before anything is written.",
    "csv.step1.acceptPdf": "Accepted: .csv, .txt and .pdf",
    "csv.err.encodingGuess": "The accented letters look broken, so I guessed the encoding. Set it by hand if the guess is wrong.",
    "csv.err.ambiguousDecimal": "The value {sample} can be read two ways. Pick the decimal mark and I will write the right amount.",
    "csv.err.noNegative": "This column has no negative values, so every row would be written as income. If a column carries the direction, give it its role; otherwise you can fix the rows in the ledger afterwards.",
    "csv.err.ambiguousDate": "This file does not settle whether day or month comes first. Pick the order and I will write the dates correctly.",
    "csv.err.readFailed": "The file could not be read. The browser may have blocked access; copy the file to another folder and try again.",
    "csv.err.tooBig": "The file is {size} and may fill the browser's storage. Back up first, then carry on.",
    "csv.err.tooManyRows": "This file has too many rows; nothing past fifty thousand is read. You can split the statement by month and import each one.",

    /* ----------------------------------------------------------- form ---- */

    "quick.keepGoing": "Keep going",
    "quick.account": "Which account",
    "a11y.plus": "Add",
    "a11y.minus": "Subtract",
    "a11y.equals": "Work it out",
    "quick.open": "Add an expense",
    "quick.title": "New expense",
    "quick.title.income": "New income",
    "quick.kind.out": "Expense",
    "quick.kind.in": "Income",
    "quick.pickDate": "Another day",
    "quick.note": "Add a note",
    "quick.chooseCategory": "Choose a category",
    "quick.recent": "What you used last",
    "quick.all": "All",
    "quick.saved": "{amount} written under {category}.",
    "quick.empty": "There is no category to write under yet. Add one in Limits and come back.",
    "quick.hint": "Type the amount, then tap a category. The tap is what saves it.",
    "a11y.keypad": "Number keys",
    "a11y.backspace": "Delete the last digit",
    "a11y.amountNow": "Amount so far: {amount}",
    "form.date": "Date",
    "form.amount": "Amount",
    "form.amount.hint": "A comma or a dot both work.",
    "form.amount.preview": "Reads as {amount}",
    "form.direction": "Direction",
    "form.direction.out": "Expense",
    "form.direction.in": "Income",
    "form.category": "Category",
    "form.note": "Note",
    "form.note.hint": "Up to {max} characters.",
    "form.fixed": "Fixed payment",
    "form.name": "Name",
    "form.kind": "Kind",
    /* The name of the colour picker's radio group and of the icon picker's
       fold toggle. Neither carries any text of its own — one is ten dots, the
       other a single glyph — so their name comes from here alone. */
    "form.color": "Colour",
    "form.icon": "Icon",
    "form.startDate": "Starts",
    "form.endDate": "Ends",
    "form.endDate.hint": "Leave it empty for no end.",
    "form.dueDate": "Due date",
    "form.limit": "Limit",
    "form.required": "required",
    "form.optional": "optional",
    "form.errors.title": "The form was not saved.",
    "form.errors.body.one": "{count} field needs a fix.",
    "form.errors.body.other": "{count} fields need a fix.",

    /* ------------------------------------------------------------ err ---- */

    "err.required": "This field is empty. It has to be filled in before the entry can be written.",
    "err.badDate": "The date could not be read. The expected form is year-month-day, or you can pick a day from the calendar.",
    "err.badAmount": "The amount could not be read. Use digits with a comma or a dot; letters and spaces are not read.",
    "err.zeroAmount": "The amount is zero. There is nothing to measure in a zero entry; write the real amount.",
    "err.negativeAmount": "The amount is written as negative. Direction comes from the Expense and Income field, so the amount stays positive.",
    "err.quantityInvalid": "The quantity could not be read. At most four decimal places are read; write it like 0.5 or 12.3456.",
    "err.quantityPrecision": "The quantity has more than four decimal places. The extra digits are refused rather than rounded away behind your back; shorten it to four.",
    "err.quantityNegative": "The quantity is written as negative. A holding is written as the amount you have; to record a sale, lower the quantity instead.",
    "err.priceRequired": "The unit price is empty. Without a price the value cannot be measured; write what one unit is worth today.",
    "err.tooLong": "The text is too long. At most {max} characters are stored; shorten it and try again.",
    "err.noteTooLong": "The note is too long. At most 200 characters are stored; shorten it and try again.",
    "form.dateHint": "Day, month, year. You can also pick from the calendar.",
    "err.badCategory": "That category no longer exists. Pick one that is still in the list.",
    "err.badDirection": "The direction does not match the category. An income category cannot hold an expense; change the category or the direction.",
    "err.badDayOfMonth": "The day of the month has to be between 1 and 31. On short months it clips to the last day.",
    "err.badMonthStartDay": "The day the period starts has to be between 1 and 28. The ceiling is 28 so that short months cannot shift the period.",
    "err.badRange": "The end date falls before the start date. Correct one of the two.",
    "err.badTarget": "The target amount is zero or negative. Write the amount you want to reach.",
    "err.limitOnIncome": "A limit belongs to a spending category. An income category has no spending to cap, so a limit here is never read.",
    "err.quotaFull": "The change could not be saved because the browser's storage is full. What is on screen is intact; download the JSON and delete old entries, and writing works again.",
    "err.writeFailed": "The change could not be saved. The browser refused the write; download your backup before closing the tab.",
    "err.readOnly": "This browser cannot store data. It may be a private window or storage that is switched off; what you write lasts only for this session, so download the JSON to move it.",
    "err.importBadFile": "This file did not read as a Moon backup. The expected fields are not in it; choose the JSON file you downloaded from the Data section.",
    "err.importNewer": "This backup comes from a newer version of Moon. This version cannot read it; update the app and try again.",
    "err.readFailed": "The file could not be read. The browser could not reach it; copy it to another folder and choose it again.",
    "err.unknown": "Something unexpected happened and the action did not finish. Reload the page; your saved data is still there.",
    "money.invalid": "The amount could not be read. Use digits with a comma or a dot; letters and spaces are not read.",

    /* ---------------------------------------------------------- empty ---- */

    "empty.panel.heading": "Nothing to measure yet.",
    "empty.panel.body": "This strip fills up the moment you write the first entry.",
    "empty.ledger.heading": "The ledger is empty.",
    "empty.ledger.body": "Moon never sends anything to a server. What you type stays in this browser, and you can export it as JSON whenever you want. Three ways to start:",
    "empty.ledger.action1": "Write one expense — takes ten seconds.",
    "empty.ledger.action2": "Import your bank statement — drop a CSV here and we'll map the columns together.",
    "empty.ledger.action3": "Open the sample month — a made-up September, 61 entries, if you'd rather look around first. One click clears it.",
    "empty.ledger.footer": "While sample data is on, a strip stays at the top. It never mixes with your own entries.",
    "empty.ledger.filtered.heading": "No entry matches this filter.",
    "empty.ledger.filtered.body": "Shorten the search or widen the period.",
    "empty.limits.heading": "No limits yet.",
    "empty.limits.body": "You can keep a ledger without limits. The moment you set one, these rows turn into scales.",
    "empty.recurring.heading": "No recurring payments.",
    "empty.recurring.body": "Write rent, subscriptions and bills once; each period they come back for your approval.",
    "empty.goals.heading": "No goals yet.",
    "empty.goals.body": "Write a goal: how much, and by when. I will measure it month to month.",
    "empty.debts.heading": "Nothing owed either way.",
    "empty.debts.body": "Who you lent to, and who owes you. These records stay out of the allowance math.",
    "empty.chart.heading": "Not enough data for a chart.",
    "empty.chart.body": "A chart needs entries from at least seven days. There are {days} so far.",
    "empty.data.heading": "Nothing to back up yet.",
    "empty.data.body": "A backup becomes possible the moment you write the first entry.",

    /* ------------------------------------------------------------ cat ---- */

    "cat.rent": "Rent",
    "cat.bills": "Bills",
    "cat.subscriptions": "Subscriptions",
    "cat.groceries": "Groceries",
    "cat.eatingOut": "Eating out",
    "cat.transport": "Transport",
    "cat.health": "Health",
    "cat.home": "Home",
    "cat.clothing": "Clothing",
    "cat.fun": "Fun",
    "cat.other": "Other",
    "cat.salary": "Salary",
    "cat.otherIncome": "Other income",

    /* ----------------------------------------------------------- a11y ---- */

    "a11y.skip": "Skip to the content",
    "a11y.rail": "Sections",
    "a11y.railMore": "Other sections",
    "a11y.strip": "Announcements and undo",
    "a11y.accounts": "Accounts and their balances",
    "a11y.periodPrev": "Previous period",
    "a11y.periodNext": "Next period",
    "a11y.periodCurrent": "Showing the period {period}",
    "a11y.disc": "{pct}% of the period has passed",
    "a11y.rowActions": "Row actions",
    "a11y.showTable": "Show this chart's numbers as a table",
    "a11y.markOver": "over the limit",
    "a11y.markRecurring": "came from a recurring payment",
    "a11y.markUnconfirmed": "came from a statement, waiting for confirmation",
    "a11y.chart.trail.desc": "The daily allowance measured on each day of the period. Lowest {min}, highest {max}, and {reference} at the start of the period.",
    "a11y.chart.flow.desc": "One bar for each day of the period. Income totals {in}, expense totals {out}.",
    "a11y.chart.cumulative.desc": "Total expense from the start of the period until today is {total}, against a pace of {pace} for the same day.",
    "a11y.chart.year.desc": "The last twelve periods across {rows} categories. Density comes from line spacing.",
    /* The value trail's own <desc>. What a chart of value answers is "how much
       now", so the newest reading is what it states. */
    "a11y.chart.value.desc": "The value of your holdings over time. The newest reading is {amount} on {date}.",
    "a11y.chart.point": "{date}, {amount}",
    "a11y.chart.pointPct": "{name}, {amount}, {pct}% of the total",
    "a11y.langChanged": "The language changed to {lang}.",
    "a11y.routeChanged": "The {section} section is open."
  };
})(window);
